### ISSUE TITLE
Winston.add2 Error

### ISSUE THREAD

**Issue by Mike43110** [nolta/Winston.jl#231]
I am not sure what I am doing wrong here.

I am trying to make a basic plot using two axis in a `FramedPlot`.
```
x = 0:0.1:10
y1 = 0.05*x.^2
y2 = -y1
p = FramedPlot()
setattr(p.x, "range", (0,10))
setattr(p.y1, "range", (0,5))
setattr(p.y2, "range", (0,-5))
add(p, Curve(x,y1))
Winston.add2(p, Curve(x,y2))
```
When using `Winston.add2` I get:
 ```
Error showing value of type FramedPlot:
ERROR: type: non-boolean (Nothing) used in boolean context
```

I am unsure if this is a usage error on my part or a bug in Winston.

Thanks

**Comment by slangangular** [comment]
I think it is a bug. By default the `log` attribute of `HalfAxis` is `nothing`, which is not a boolean. For the first axes this is fixed by applying the settings from the FramedPlot block in Winston.ini. 
My attempt at a fix is here: 202a03be74a1274cab641a39749cf74e6938189e.
I don't have time to test if this breaks anything right now, so I'm not yet creating a pull request, maybe tomorrow.

**Comment by Mike43110** [comment]
Well, making that change does allow me to plot thanks!

I ran the tests but I have absolutely no idea if they passed or not (nothing said fail or crashed at least).

**Comment by slangangular** [comment]
Well I think I made a mistake in my original fix. It worked if you actually had two axes, but if you made a single plot with for example `semilogy` in which the primary axis was logarithmic, the secondary axis would remain non-logarithmic. 
The PR is #232, but I'd be happy if somebody could take a look at it and test it a bit.
