### ISSUE TITLE
Is Winston active?

### ISSUE THREAD

**Issue by scidom** [nolta/Winston.jl#268]
What is the current state of Winston? Is it being developed or maintained? I use Gadfly, which covers my plotting needs, though I like Winston too because of its speed.

**Comment by heliosdrm** [comment]
There is no tagged release since nearly one year ago, that's true. But this does not mean that nolta is not active, although according to his activity history in Github, he seems rather occupied with other projects in the last months.

Regarding Winston, there is also activity from other contributors: the master branch incorporates some bug fixes and changes to improve compatibility with Julia 4.0. There are also newer pull requests, although the checks with Julia 5.0 are still a trouble -- also in other packages, due to big changes in many aspects of vector operations, above all.

**Comment by ararslan** [comment]
Note that Winston has been updated to work on Julia 0.5 and 0.6. I'll continue to help out with maintenance of it as much as I can going forward to ensure it keeps working.

**Comment by nolta** [comment]
If it would help, I can move Winston to JuliaGraphics.

**Comment by ararslan** [comment]
That seems like a good solution to me. 👍

**Comment by nolta** [comment]
Done.

**Comment by ararslan** [comment]
Thanks Mike! Long live Winston!
